[[rules]]
    description = "AWS Manager ID"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["key", "AWS"]
        [[rules.whitelist]]
            description = "ignore md files"
            file = '''(.*)?md$'''
        [[rules.whitelist]]
            description = "ignore this regex"
            regex = '''ignore$'''
        [[rules.whitelist]]
            description = "ignore regex and md files"
            regex = '''ignore$'''
            file = '''(.*)?md$'''
